In [1]:
import numpy as np

In [2]:
np_data = np.array([0,1,2,3,4])
np_data

array([0, 1, 2, 3, 4])

In [4]:
np_data + np_data

array([0, 2, 4, 6, 8])

In [5]:
np_data * np_data

array([ 0,  1,  4,  9, 16])

In [7]:
np_data - np_data

array([0, 0, 0, 0, 0])

In [8]:
np_data / np_data

/Users/ethan/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([nan,  1.,  1.,  1.,  1.])

In [9]:
np_data * 2

array([0, 2, 4, 6, 8])

In [12]:
np_data [1]

1

In [13]:
np_data[:2]

array([0, 1])

In [16]:
np_arraytest = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
np_arraytest

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [17]:
np_arraytest + np_arraytest

array([[ 2,  4,  6,  8],
       [10, 12, 14, 16],
       [18, 20, 22, 24]])

In [18]:
np_arraytest * np_arraytest

array([[  1,   4,   9,  16],
       [ 25,  36,  49,  64],
       [ 81, 100, 121, 144]])

In [19]:
np_arraytest * 0.5

array([[0.5, 1. , 1.5, 2. ],
       [2.5, 3. , 3.5, 4. ],
       [4.5, 5. , 5.5, 6. ]])

In [20]:
np_arraytest[2]

array([ 9, 10, 11, 12])

In [21]:
np_arraytest[2][2]

11

In [22]:
type(np_arraytest[2][2])

numpy.int64

In [23]:
np_arraytest[:2]

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [24]:
np.log(np_arraytest)

array([[0.        , 0.69314718, 1.09861229, 1.38629436],
       [1.60943791, 1.79175947, 1.94591015, 2.07944154],
       [2.19722458, 2.30258509, 2.39789527, 2.48490665]])

In [26]:
np_test = np.array([[1,2,3,4],[5,6,7,8],[ 9,10,11,33]])
np_test

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 33]])

In [27]:
np.absolute(np_test * -0.5)

array([[ 0.5,  1. ,  1.5,  2. ],
       [ 2.5,  3. ,  3.5,  4. ],
       [ 4.5,  5. ,  5.5, 16.5]])

In [28]:
np.log(np_test)

array([[0.        , 0.69314718, 1.09861229, 1.38629436],
       [1.60943791, 1.79175947, 1.94591015, 2.07944154],
       [2.19722458, 2.30258509, 2.39789527, 3.49650756]])

In [29]:
np.sqrt(np_test)

array([[1.        , 1.41421356, 1.73205081, 2.        ],
       [2.23606798, 2.44948974, 2.64575131, 2.82842712],
       [3.        , 3.16227766, 3.31662479, 5.74456265]])

In [30]:
np_test.sum()

99

In [31]:
np_test.mean()

8.25

In [32]:
np_test.std()

8.053208470334459

In [33]:
np_test[0].sum()

10

In [38]:
matrix1 = np.array([[1,2,3],[4,5,6]])
matrix2 = np.array([[7,8,8],[38,22,45]])
matrix2

array([[ 7,  8,  8],
       [38, 22, 45]])

In [37]:
matrix1

array([[1, 2, 3],
       [4, 5, 6]])

In [39]:
matrix2.transpose()

array([[ 7, 38],
       [ 8, 22],
       [ 8, 45]])

In [40]:
np.dot(matrix1, matrix2.transpose())

array([[ 47, 217],
       [116, 532]])